mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from web_app import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('special/', views.special,name='special'),
    path('web_app/', include('web_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

web_app/urls.py
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'web_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('contact/',views.contact,name='contact'),
    path('projects/',views.projects,name='projects'),
    path('summary/',views.summary,name='summary'),
    path('prolists/',views.prolists,name='Project Lists'),
]

web_app/models.py
from django.db import models
from django.contrib.auth.models import User
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='web_app/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

web_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

web_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):

    # {% if user.is_authenticated %}
    #     <h2>Hi {{ user.username.upper }}, <br>Welcome to my website !</h2>
    # {% else %}
    #
    # {% endif %}

    # if request.method == 'POST':
    #     # First get the username and password supplied
    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #
    #     # Django's built-in authentication function:
    #     user = authenticate(username=username, password=password)
    #
    #     # If we have a user
    #     if user:
    #         #Check it the account is active
    #         if user.is_active:
    #             # Log the user in.
    #             login(request,user)
    #             # Send the user back to some page.
    #             # In this case their homepage.
    #             return HttpResponseRedirect(reverse('prolists'))
    #         else:
    #             # If account is not active:
    #             return HttpResponse("Your account is not active.")
    #     else:
    #         print("Someone tried to login and failed.")
    #         print("They used username: {} and password: {}".format(username,password))
    #         return HttpResponse("Invalid login details supplied.")
    #
    # else:
    #     #Nothing has been provided for username or password.
    #     return render(request, 'web_app/login.html', {})

        return render(request,'web_app/index.html')


@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/web_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'web_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'web_app/login.html', {})

def contact(request):
    return render(request,'web_app/contact.html')

def projects(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('prolists'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'web_app/login.html', {})

def prolists(request):
    return render(request,'web_app/summary.html')

def summary(request):
    return render(request,'web_app/summary.html')

web_app/templates/web_app/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <!-- Latest compiled and minified CSS ###this is for gradient color changes-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>


    <!-- Latest compiled and minified CSS ###this is for navbar-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS ### this is for seporate navbar-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

    <!-- new javascript -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script> -->


    <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> -->

    <link rel="stylesheet" href="{% static 'web_app/css/gradient.css'%}">

  </head>
  <body>
    <div id="gradient" />

    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>

        </div>

        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'web_app:register' %}">Register</a>
     <!--        <a class="nav-link" href="{% url 'web_app:projects' %}">Projects</a>  -->
       <a class="nav-item nav-link" href="http://52.22.253.52:8008">Blog</a>
        <a class="nav-link" href="{% url 'web_app:summary' %}">Summary</a>
        <a class="nav-link" href="{% url 'web_app:contact' %}">Contact Me</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'web_app:user_login' %}">Login</a>
        {% endif %}

      </div>

      </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

  </body>

  <script src="{% static "web_app/js/gradient.js"%}" type="text/javascript" ></script>

  <!-- Latest compiled and minified jQuery -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
  <!-- Latest compiled and minified JavaScript -->
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->

</html>

web_app/templates/web_app/contact.html
<!-- {% extends 'web_app/base.html' %}
<!-- {% block body_block %} -->
  <div class="container">
    <div class="jumbotron">
      <h1>Xiangqian Liu</h1>

      <p>Cellphone: 610-203-3902</p>
      <p>Email: liuxq31@gmail.com</p>


        <!-- <form method="post" action="{% url 'web_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username: </label>
          <input type="text" name="username" placeholder="Username"><br><br>

          <label for="password">Password: </label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form> -->

    </div>
  </div>
{% endblock %} -->

web_app/templates/web_app/index.html
{% extends "web_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">

    {% if user.is_authenticated %}

        <h2>Welcome {{ user.username.upper }} to Xiangqian Liu's Website</h2>
    {% else %}

    {% endif %}

    <h1>AWS Admin/SysOps/DevOps</h1>
    <h2>Certificates</h2>
    <p><a href="https://forword.s3.amazonaws.com/AWS+Certified+SysOps+Administrator+-+Associate+certificate+(1).pdf">AWS Certified SysOps Administrator - Associate (Validation Number 7XP4S4Q232F1QS90)</a></p>
    <p><a href="https://forword.s3.amazonaws.com/AWS+Certified+Solutions+Architect+-+Associate+certificate+(1).pdf">AWS Certified Solution Architect - Associate (Validation Number JVTSBHCKG144QNKH)</a></p>
    <p><a href="https://forword.s3.amazonaws.com/Python+Django+Full+Stac+Web+Developer+Bootcamp-11092019.jpg">Python and Django Full Stack Web Developer Bootcam, Certificate of Course Completion (32 hrs)</a></p>

    <p>Skilled and passionate AWS cloud engineer with lots of hands-on experience in implementing, supporting, automating, and optimizing the deployments in AWS, leveraging configuration management, Continuous integration/continuous deployment (CICD), and SysOps/DevOps processes.</p>
    <h3>KEY SKILLS</h3>
    <ul class="skills">
      <li>AWS services – EC2, S3, RDS, Route 53, SQS, SNS, CloudWatch, CloudTrail, Autoscaling, ALB, etc.</li>
      <li>AWS security/networking configuration – IAM, Security group, NACL, VPC, WAF, VPN, etc.</li>
      <li>AWS monitoring/logs – CloudWatch, CloudTrail, VPC Flow Log, Access Logs (S3, CloudFront, RDS).</li>
      <li>Developing CICD pipeline with opensource DevOps tools for automated continuous development, testing, deployment and monitoring – Git, Puppet, Ansible, Docker, Selenium, Jenkins, Kubernetes and Nagios.</li>
      <li>Configuration/patching/updating automation – Puppet, Ansible, CloudFormation, AWS SSM.</li>
      <li>Build web applications with HTML, CSS, Bootstrap, Python and Django</li>
      <li>Good understanding of Linux (RedHat, Centos, Oracle, Ubuntu), Python, shell scripting.</li>
    </ul>

    <h3>PROFESSIONAL TRAINING AND CERTIFICATES</h3>
    <ul class="skills">
      <li>AWS Certified SysOps Administrator – Associate (Validation Number 7XP4S4Q232F1QS90) 	Aug. 2019 </li>
      <li>AWS Certified Solution Architect – Associate (Validation Number JVTSBHCKG144QNKH) 	Jul. 2019  </li>
      <li>DevOps Certification Training Course Online (Intellipaat/42 hrs training/60 hrs hands-on project)  Sep. 2019</li>
      <li>Python and Django Full Stack Web Developer Bootcamp (<a href="https://forword.s3.amazonaws.com/Python+Django+Full+Stac+Web+Developer+Bootcamp-11092019.jpg">32 hrs, Certification of completion</a>) Nov. 2019</li>
      <li>AWS Certified DevOps Engineer Professional 2020 - Hands On (Udemy, 20.5 hrs) Oct. 2019</li>
      <li>Complete Linux Training Course (Udemy, 22.5 hrs) Jul. 2019</li>
      <li>Linux administration training & Python programming training (from Intellipaat/Udemy)	Jul.   2019</li>

    </ul>

    <p></p>
    <p></p>

  </div>
</div>

{% endblock %}

web_app/templates/web_app/login.html
{% extends 'web_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'web_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username: </label>
          <input type="text" name="username" placeholder="Username"><br><br>

          <label for="password">Password: </label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

web_app/templates/web_app/projects.html
{% extends 'web_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Comming Soon!</h1>
      <h1>Please Login</h1>

      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a class="nav-link" href="{% url 'web_app:user_login' %}">Login</a>
      {% endif %}

        <form method="post" action="{% url 'web_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username: </label>
          <input type="text" name="username" placeholder="Username"><br><br>

          <label for="password">Password: </label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

web_app/templates/web_app/registration.html
{% extends "web_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Please Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

web_app/templates/web_app/summary.html
{% extends 'web_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <!-- <h1>Summary & Projects</h1> -->
<!--
        <form method="post" action="{% url 'web_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username: </label>
          <input type="text" name="username" placeholder="Username"><br><br>

          <label for="password">Password: </label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form> -->

<h3>SUMMARY</h3>
  <ul class="textcontent">
    <li>Skilled in AWS EC2, S3, RDS, Elastic IPs, EBS, Security Group, Access Control List, Route 53, VPC, ELB/ALB, Elastic Beanstalk, DynamoDB, and CloudFormation in AWS cloud infrastructure.</li>
    <li>Networking – setting up VPC, subnets, VPC peering, VPN connection, and configure AWS IAM, MFA, Security Groups, Network Access Control List (NCAL) in Public and Private Subnets in VPC. Experience working with IAM in to create new accounts, roles, groups, and assign individual policies to each group.
</li>
    <li>Designing, deploying, managing and operating scalable, highly available and fault-tolerant systems on AWS.
</li>
    <li>Experience in monitoring metrics on EC2, EBS, Elastic Load Balancer, RDS using CloudWatch with basic metrics and custom metrics such as memory usage, Swap usage, etc.
</li>
    <li>Deploying multiple applications utilizing most of the AWS stack (including EC2, Rout 53, S3, RDS, DynamoDB, SNS, SQS, IAM) focusing on high-availability, fault tolerance, elastic load balancing and auto scaling.
</li>
    <li>Experience in building CICD pipeline with DevOps tools such as version control system (Git), containerization (Docker), automated build, integration & deployment (Jenkins), AWS Code Pipeline, and elastic Beanstalk.
</li>
    <li>Experience in Cloud infrastructure automation using Puppet, Ansible and AWS CloudFormation templates.</li>
    <li>Hands-on skills of software containerization platforms like Docker and container orchestration tools like Kubernetes and Docker Swarm.</li>
    <li>Install & configure Nagios to constantly monitor network bandwidth, memory usage, & hard drive status.</li>
    <li>Build, test, and deploy Docker applications with Kubernetes, Jenkins, Travis CI to AWS.</li>
    <li>Build web applications with HTML, CSS, JQerry, JAVA, Python and Django.</li>
    <li>Migrate VirtualBox VM (linux and windows) and on-premise applications to AWS cloud.</li>
    <li>Estimating AWS usage costs and identifying operational cost control mechanisms.</li>
    <li>Oracle WebLogic/Fusion Middleware, UNIX, Linux, Apache installation, configuration.</li>
    <li>Hands-on experience in linux (RedHat/Centos/Oracle/Ubuntu)</li>
    <li>Working knowledge of Python, Bash scripting.</li>
    <li></li>

  </ul>
  <h3>EDUCATION</h3>
    <ul class="textcontent">
    <li>Ph.D. in Chemistry, Peking University 							     Jun. 1998</li>
    </ul>
    <div class="">

  <h3>PROFESSIONAL EXPERIENCE</h3>
      <ul class="textcontent">
        <h4>Projects on AWS Cloud (hands-on with AWS personal account) 					10/01/2018 – Current</h4>
        <li>Build Three-Tier High Availability and Fault Tolerance VPC Architect on AWS – Create 3-tier VPC with public and private subnets. Secure VPC resources with security groups (ELB, NAT, Bastion, AppServer and database security groups). Monitoring VPC with VPC flow logs (create IAM role for VPC flow logs, CloudWatch Log Group, VPC Flow Log). Building High Availability with Multiple Availability Zones. Create an Application ELB and Auto Scaling group (create ALB, Auto Scaling launch configuration, Auto Scaling Group, set up scaling policy). Deploying Multi AZ Aurora Serverless Cluster (create DB subnet group, deploy Aurora serverless database). Accessing VPC resources with Cloud9 Bastion Host (create Cloud9 environment, add security group). Increasing security with public & private Network Access Control Lists (NACLs).
        <li>Build CI/CD pipeline configurations from Jenkins – source code version control with Git, containerization with Docker, continuous testing with Selenium, build jobs with shell scripting, build triggers, environments, and after job action settings for continuous integration and deployment using Jenkins to AWS cloud.</li>
        <li>Build personal website with some applications (ongoing)</li>
        <li>Automated Configuring two server groups for Apache2 and Nginx using Puppet and Ansible to AWS – using Puppet to configure two servers and update website html files; also using Ansible to configure same.
</li>
        <li>Provision infrastructure with CloudFormation on AWS – create a VPC; deploying the architecture with CloudFormation; create an Internet Gateway and a Route to Subnet; updating the architecture with CloudFormation; Create an EC2 instance and security group; Deploying the Wordpress Server.
</li>
        <li>Migrate on premise VM to AWS – VM Import/Export/Create EC2 instances based on on-premise server – Extract vmdk file from on-premise VMware or VirtualBox. Create S3 bucket and upload vmdk file with AWS console/AWS CLI. Create trust-policy.json file, vmimport role, role-policy.json file, and attach role-policy.json to vmimport role. create containers.json file, create AMI from uploaded vmdk file. create EC2 instance from newly created AMI.
</li>

      </ul>
      <h4>IT Technical Support, 01/2018 – Current,  Family Business</h4>
      <ul>
        <li>IT support, software installation, configuration, updating, software application training and maintenance. </li>
      </ul>
    </div>

      <h4>Dow Chemical Company, Collegeville, PA 						       06/2003 – 12/2017, Senior Scientist</h4>
      <ul>
        <li>(26 patent applications/15 granted patents) Developed new materials and formulations for electronic applications. Collaborated with internal downstream business to develop applications. Networked with other scientists to generate shelf-life, physical property, toxicology, and other regulatory information for new chemical substances. Mentored technologists and junior scientists in synthesis, purification, and characterization of new materials. Led and managed projects and experiments for R&D portfolio goals; organize project plans in alignment with business objectives and timelines; coordinated the scale up and commercialization, and consistently searched for scientific and patent literature. </li>
      </ul>

    </div>
  </div>
{% endblock %}